app = "vouchflow-web"
primary_region = "iad"

[build]

[env]
  NODE_ENV     = "production"
  HOST         = "0.0.0.0"
  PORT         = "3000"
  API_BASE_URL = "https://api.vouchflow.dev"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = false
  auto_start_machines  = true
  min_machines_running = 1
  processes            = ["app"]
  allowed_ip_ranges    = [
    # Cloudflare IPv4
    "173.245.48.0/20",
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "162.158.0.0/15",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "172.64.0.0/13",
    "131.0.72.0/22",
    # Cloudflare IPv6
    "2400:cb00::/32",
    "2606:4700::/32",
    "2803:f800::/32",
    "2405:b500::/32",
    "2405:8100::/32",
    "2a06:98c0::/29",
    "2c0f:f248::/32",
  ]

  [[http_service.checks]]
    grace_period = "10s"
    interval     = "30s"
    method       = "GET"
    path         = "/health"
    protocol     = "http"
    timeout      = "5s"

[[vm]]
  memory   = "256mb"
  cpu_kind = "shared"
  cpus     = 1
